export const PRODI_OPTIONS = [
  "Informatika",
  "Sistem Informasi",
  "Teknologi Informasi",
  "Rekayasa Perangkat Lunak",
  "Desain Komunikasi Visual (DKV)",
  "Ilmu Komunikasi",
  "Manajemen Bisnis",
  "Akuntansi",
  "Teknik Elektro",
  "Teknik Industri",
  "Teknik Komputer",
  "Arsitektur",
  "Desain Produk",
  "Hubungan Internasional",
  "Psikologi",
  "Hukum",
  "Sastra Inggris",
  "Pemasaran Digital",
];

export const SEMESTER_OPTIONS = [
  "Semester 1",
  "Semester 2",
  "Semester 3",
  "Semester 4",
  "Semester 5",
  "Semester 6",
  "Semester 7",
  "Semester 8",
  "Semester 8+ (Tingkat Akhir)",
];

export const KAMPUS_OPTIONS = [
  "Universitas Bina Sarana Informatika (UBSI)",
  "Universitas Indonesia (UI)",
  "Institut Teknologi Bandung (ITB)",
  "Universitas Gadjah Mada (UGM)",
  "Institut Pertanian Bogor (IPB)",
  "Institut Teknologi Sepuluh Nopember (ITS)",
  "Universitas Airlangga (UNAIR)",
  "Universitas Diponegoro (UNDIP)",
  "Universitas Padjadjaran (UNPAD)",
  "Universitas Brawijaya (UB)",
  "BINUS University",
  "Telkom University",
  "Universitas Sebelas Maret (UNS)",
  "Universitas Negeri Jakarta (UNJ)",
  "Universitas Negeri Yogyakarta (UNY)",
  "Universitas Islam Indonesia (UII)",
  "Universitas Katolik Parahyangan (UNPAR)",
  "Universitas Trisakti",
  "Universitas Tarumanagara (UNTAR)",
  "Universitas Dian Nuswantoro (UDINUS)",
  "UPN Veteran Jakarta",
  "UPN Veteran Yogyakarta",
  "Universitas Esa Unggul",
  "Universitas Mercu Buana",
  "Universitas Gunadarma",
  "Universitas Pamulang (UNPAM)",
];

export const BANK_OPTIONS = [
  "Bank Central Asia (BCA)",
  "Bank Mandiri",
  "Bank Rakyat Indonesia (BRI)",
  "Bank Negara Indonesia (BNI)",
  "Bank Syariah Indonesia (BSI)",
  "Bank Jago",
  "SeaBank",
  "CIMB Niaga",
  "Bank Permata",
  "Bank Danamon",
  "Bank Tabungan Negara (BTN)",
  "Bank BTPN / Jenius",
  "Bank Mega",
  "Bank Panin",
  "Bank OCBC NISP",
  "DANA (E-Wallet)",
  "GoPay (E-Wallet)",
  "OVO (E-Wallet)",
  "ShopeePay (E-Wallet)",
];

export const INDUSTRI_OPTIONS = [
  "F&B / Kuliner",
  "Fashion & Tekstil",
  "Ritel & Toko Kelontong",
  "Jasa Kreatif & Percetakan",
  "Kecantikan & Skincare",
  "Otomotif & Bengkel",
  "Teknologi & Digital",
  "Agribisnis & Peternakan",
  "Kerajinan Tangan / Kriya",
  "Pendidikan & Kursus",
  "Kesehatan & Herbal",
  "Properti & Konstruksi",
  "Event & Fotografi",
  "Jasa Logistik & Kurir",
];

export const KOTA_OPTIONS = [
  "Jakarta Selatan",
  "Jakarta Pusat",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Utara",
  "Bekasi",
  "Depok",
  "Bogor",
  "Tangerang",
  "Tangerang Selatan",
  "Bandung",
  "Surabaya",
  "Semarang",
  "Yogyakarta",
  "Surakarta (Solo)",
  "Malang",
  "Medan",
  "Palembang",
  "Makassar",
  "Denpasar",
  "Balikpapan",
  "Samarinda",
  "Bandar Lampung",
  "Pekanbaru",
  "Batam",
  "Pontianak",
  "Banjarmasin",
  "Manado",
  "Mataram",
];
