"""Initial 13 tables schema

Revision ID: 6abe14a0674e
Revises: 
Create Date: 2026-08-23 12:55:44.245559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abe14a0674e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_prodi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_prodi', sa.String(length=100), nullable=False),
    sa.Column('fakultas', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_prodi')
    )
    op.create_index(op.f('ix_master_prodi_id'), 'master_prodi', ['id'], unique=False)
    op.create_table('master_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('nama_skill', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_skill')
    )
    op.create_index(op.f('ix_master_skills_id'), 'master_skills', ['id'], unique=False)
    op.create_index(op.f('ix_master_skills_kategori'), 'master_skills', ['kategori'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('UMKM', 'MHS', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(length=100), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('tipe', sa.Enum('PROPOSAL', 'PAYMENT', 'SUBMISSION', 'DISPUTE', 'SYSTEM', name='notification_type_enum'), nullable=False),
    sa.Column('url_referensi', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profile_mhs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prodi_id', sa.Integer(), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=True),
    sa.Column('url_ktm', sa.Text(), nullable=True),
    sa.Column('url_foto', sa.Text(), nullable=True),
    sa.Column('url_portofolio', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_proyek_selesai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prodi_id'], ['master_prodi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('profile_umkm',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nama_usaha', sa.String(length=100), nullable=False),
    sa.Column('bidang_industri', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kota', sa.String(length=100), nullable=True),
    sa.Column('no_kontak', sa.String(length=20), nullable=True),
    sa.Column('url_foto_usaha', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('umkm_id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('deskripsi_raw', sa.Text(), nullable=False),
    sa.Column('kategori', sa.Enum('DESIGN', 'UIUX', 'PEMROGRAMAN', 'VIDEO', 'COPYWRITING', 'ADMIN_DATA', name='project_category_enum'), nullable=False),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'BIDDING', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CANCELLED', name='project_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_max > 0 AND budget_max <= 2000000', name='check_budget_limit'),
    sa.ForeignKeyConstraint(['umkm_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_kategori'), 'projects', ['kategori'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_umkm_id'), 'projects', ['umkm_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saldo_aktif', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_escrow', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('ai_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['master_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_requirements_id'), 'ai_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_ai_requirements_project_id'), 'ai_requirements', ['project_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pelapor_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('dekripsi_masalah', sa.Text(), nullable=False),
    sa.Column('resolusi_masalah', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='dispute_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pelapor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_project_id'), 'disputes', ['project_id'], unique=False)
    op.create_table('ledger_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('tipe', sa.Enum('TOPUP', 'HOLD', 'RELEASE', 'WITHDRAW', 'REFUND', name='transaction_type_enum'), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('referensi_gateway', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_logs_id'), 'ledger_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_logs_wallet_id'), 'ledger_logs', ['wallet_id'], unique=False)
    op.create_table('mhs_skill',
    sa.Column('mhs_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('tingkat', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skill_level_enum'), nullable=False),
    sa.ForeignKeyConstraint(['mhs_id'], ['profile_mhs.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['master_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mhs_id', 'skill_id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('mhs_id', sa.UUID(), nullable=False),
    sa.Column('harga_tawar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('estimasi_hari', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='proposal_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mhs_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_mhs_id'), 'proposals', ['mhs_id'], unique=False)
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dari_user_id', sa.UUID(), nullable=False),
    sa.Column('ke_user_id', sa.UUID(), nullable=False),
    sa.Column('skor', sa.Integer(), nullable=False),
    sa.Column('ulasan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('skor >= 1 AND skor <= 5', name='check_rating_skor_range'),
    sa.ForeignKeyConstraint(['dari_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ke_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'dari_user_id', name='unique_rating_per_user_per_project')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_project_id'), 'ratings', ['project_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('url_berkas', sa.Text(), nullable=False),
    sa.Column('url_source_file', sa.Text(), nullable=True),
    sa.Column('catatan_pengiriman', sa.Text(), nullable=True),
    sa.Column('jumlah_revisi', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVISION_REQUESTED', 'APPROVED', name='submission_status_enum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('jumlah_revisi >= 0 AND jumlah_revisi <= 2', name='check_max_revision_limit'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_ratings_project_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_mhs_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('mhs_skill')
    op.drop_index(op.f('ix_ledger_logs_wallet_id'), table_name='ledger_logs')
    op.drop_index(op.f('ix_ledger_logs_id'), table_name='ledger_logs')
    op.drop_table('ledger_logs')
    op.drop_index(op.f('ix_disputes_project_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_ai_requirements_project_id'), table_name='ai_requirements')
    op.drop_index(op.f('ix_ai_requirements_id'), table_name='ai_requirements')
    op.drop_table('ai_requirements')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_projects_umkm_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_kategori'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('profile_umkm')
    op.drop_table('profile_mhs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_master_skills_kategori'), table_name='master_skills')
    op.drop_index(op.f('ix_master_skills_id'), table_name='master_skills')
    op.drop_table('master_skills')
    op.drop_index(op.f('ix_master_prodi_id'), table_name='master_prodi')
    op.drop_table('master_prodi')
    # ### end Alembic commands ###
