import { StyleSheet } from "react-native";
import { COLORS, SHADOWS } from "../../theme/colors";
import { FONTS } from "../../theme/fonts";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#0B132B",
  },
  heroSection: {
    width: "100%",
    position: "relative",
  },
  heroImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11, 19, 43, 0.75)",
  },
  heroContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingTop: 10,
  },
  brandLogo: {
    width: 140,
    height: 40,
    marginBottom: 16,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    marginBottom: 12,
  },
  heroBadgeText: {
    fontFamily: FONTS.bodyBold,
    fontSize: 10,
    color: "#6EE7B7",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  welcomeText: {
    fontFamily: FONTS.displayBold,
    fontSize: 26,
    color: "#F8FAFC",
    letterSpacing: -0.5,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 13,
    color: "#CBD5E1",
    lineHeight: 20,
    textAlign: "center",
  },
  bottomSheet: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    marginTop: -32, // Seamless overlap
    overflow: "hidden",
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 40,
  },
  testAccountBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 20,
    ...SHADOWS.sm,
  },
  testHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  testTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  testTitle: {
    fontFamily: FONTS.bodyBold,
    fontSize: 13,
    color: "#1E293B",
  },
  testPassNotice: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 11,
    color: "#64748B",
  },
  chipRow: {
    flexDirection: "column",
    gap: 10,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  chipActiveMhs: {
    borderColor: COLORS.brandIndigo,
    backgroundColor: "#EEF2FF",
  },
  chipActiveUmkm: {
    borderColor: COLORS.success,
    backgroundColor: "#ECFDF5",
  },
  chipIconBgIndigo: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  chipIconBgGreen: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
  },
  chipLabel: {
    fontFamily: FONTS.bodyBold,
    fontSize: 12,
    color: "#0F172A",
  },
  chipEmail: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
  },
  formArea: {
    marginBottom: 20,
  },
  forgotPasswordRow: {
    alignItems: "flex-end",
    marginBottom: 16,
    marginTop: 2,
  },
  forgotPasswordLink: {
    fontFamily: FONTS.bodyBold,
    fontSize: 12,
    color: COLORS.brandIndigo,
  },
  loginBtn: {
    marginTop: 4,
    width: "100%",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 20,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  dividerText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 12,
    color: "#94A3B8",
  },
  registerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  registerText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 13,
    color: "#64748B",
  },
  registerLink: {
    fontFamily: FONTS.bodyBold,
    fontSize: 13,
    color: COLORS.brandIndigo,
  },
  securityBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 20,
  },
  securityText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: 11,
    color: "#94A3B8",
    textAlign: "center",
    lineHeight: 16,
  },
});
